filebeat:
    prospectors:
        - 
            type: log
            enabled: true
            paths:
                - 
                    /usr/share/filebeat/watch/*.log
                -
                    /usr/share/filebeat/watch/*/*.log

output:
    logstash:
        hosts: ["logstash:5044"]